"""Load the CIRA-CIC-DoHBrw-2020 / DoH-Tunnel-Traffic-HKD feature CSVs.

The dataset ships three files, all with the same 34 DoHLyzer columns plus a
label:

  l1-total-add.csv  DoH vs non-DoH traffic (not used here)
  l2-total-add.csv  benign DoH (19,807 rows) vs malicious/tunneled DoH
                     (354,996 rows), labeled Benign / Malicious
  l3-total-add.csv  the malicious rows only, labeled by which tunneling
                     tool produced them (dns2tcp, dnscat2, iodine, dnstt,
                     tcp-over-dns, tuns)

l2's Malicious rows and l3's rows cannot be joined key-by-key: about
99,902 rows in each file are exact duplicates of another row (idle/empty
flows produce identical stats), so a join on IP/port/timestamp or even the
full feature row is many-to-many and silently multiplies rows. There is no
reliable way to recover which l2 row corresponds to which l3 row.

The fix used here is to not join at all. l2's Benign rows and l3's rows
(already tool-labeled) share the exact same 34-column schema, so the
per-tool dataset is built by loading them as two independent label sources
and concatenating: 19,807 benign rows from l2, 354,996 malicious rows with
a tool name from l3. This gives every row a class label and, for malicious
rows, a tool label, without ever needing to match a benign row to a
specific malicious row.

THE LEAK
-------------------------------------------------------------------------------
CIRA-CIC-DoHBrw-2020 was generated by running benign DoH clients and
tunneling tools as separate capture sessions, each with its own fixed set
of client/server IPs. Benign traffic and malicious traffic come from
disjoint IP ranges: there is zero overlap between the source/destination
IPs seen on the benign side and the ones seen on the malicious side. A
model that gets SourceIP, DestinationIP, SourcePort, DestinationPort, or
the absolute TimeStamp can trivially memorize "which address pair belongs
to which capture session" and score close to 100% while learning nothing
about what tunneling traffic looks like. `DROPPED_LEAKY_FEATURES` names
exactly the columns that make this possible, and `load_features` refuses
to hand them to a caller.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import pandas as pd

# Columns that identify a session rather than describe its behavior. Any of
# these lets a model shortcut on "which capture did this come from" instead
# of "what does tunneling traffic look like". Named as a constant, not just
# documented, so code and tests can both point at the same list.
DROPPED_LEAKY_FEATURES: tuple[str, ...] = (
    "SourceIP",
    "DestinationIP",
    "SourcePort",
    "DestinationPort",
    "TimeStamp",
)

# The remaining DoHLyzer statistical features: packet-size stats, inter-
# packet-timing stats, DoH response-time stats, plus duration and the two
# byte-rate columns. Every one of these describes the SHAPE of a flow, not
# who was on the other end of it, so none of them can encode "which capture
# session" the way an IP or a timestamp can.
BEHAVIORAL_FEATURES: tuple[str, ...] = (
    "Duration",
    "FlowBytesSent",
    "FlowSentRate",
    "FlowBytesReceived",
    "FlowReceivedRate",
    "PacketLengthVariance",
    "PacketLengthStandardDeviation",
    "PacketLengthMean",
    "PacketLengthMedian",
    "PacketLengthMode",
    "PacketLengthSkewFromMedian",
    "PacketLengthSkewFromMode",
    "PacketLengthCoefficientofVariation",
    "PacketTimeVariance",
    "PacketTimeStandardDeviation",
    "PacketTimeMean",
    "PacketTimeMedian",
    "PacketTimeMode",
    "PacketTimeSkewFromMedian",
    "PacketTimeSkewFromMode",
    "PacketTimeCoefficientofVariation",
    "ResponseTimeTimeVariance",
    "ResponseTimeTimeStandardDeviation",
    "ResponseTimeTimeMean",
    "ResponseTimeTimeMedian",
    "ResponseTimeTimeMode",
    "ResponseTimeTimeSkewFromMedian",
    "ResponseTimeTimeSkewFromMode",
    "ResponseTimeTimeCoefficientofVariation",
)

BENIGN_TOOL_LABEL = "benign"


@dataclass(frozen=True)
class DoHDataset:
    """The assembled, label-carrying dataset, ready for feature selection.

    `frame` still contains the leaky identity columns at this point; they
    are only stripped when `feature_matrix()` is called. Keeping them in
    the raw frame lets other code (e.g. a check confirming the disjoint-IP
    claim) inspect them explicitly, while every path that trains a model
    goes through `feature_matrix()`, which is the one place the drop is
    enforced.
    """

    frame: pd.DataFrame

    def __post_init__(self) -> None:
        missing = [c for c in BEHAVIORAL_FEATURES if c not in self.frame.columns]
        if missing:
            raise ValueError(f"dataset is missing expected behavioral columns: {missing}")
        if "label" not in self.frame.columns or "tool" not in self.frame.columns:
            raise ValueError("dataset frame must carry 'label' and 'tool' columns")

    def __len__(self) -> int:
        return len(self.frame)

    def feature_matrix(self) -> pd.DataFrame:
        """Behavioral features only. This is the enforcement point for the
        anti-leak rule: no identity column is reachable from here even if a
        caller tries, because they were never selected in the first place.
        """
        return self.frame[list(BEHAVIORAL_FEATURES)].copy()

    def labels(self) -> pd.Series:
        """Binary 0/1 label: 1 = malicious (tunneled) DoH, 0 = benign DoH."""
        return (self.frame["label"] == "Malicious").astype(int)

    def tools(self) -> pd.Series:
        """Which tunneling tool produced each row, or 'benign' for benign
        rows. This is what leave-one-tool-out grouping splits on.
        """
        return self.frame["tool"]


def _read_csv(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path)
    # l3's header has a UTF-8 BOM on the first column name; l2's does not.
    # Strip both so downstream code can refer to columns by plain name
    # regardless of which file they came from.
    df.columns = [c.strip().lstrip("﻿") for c in df.columns]
    return df


def load_dataset(data_dir: Path | str) -> DoHDataset:
    """Build the combined benign/malicious, per-tool-labeled dataset.

    Reads l2-total-add.csv for the 19,807 benign rows and l3-total-add.csv
    for the 354,996 malicious rows (already labeled by tunneling tool).
    See the module docstring for why these are concatenated rather than
    joined. Rows with missing values in any behavioral feature are dropped
    (688 such rows exist in l2, spread across both classes at roughly
    their base rate, so dropping them is not itself a source of bias).
    """
    data_dir = Path(data_dir)
    l2_path = data_dir / "l2-total-add.csv"
    l3_path = data_dir / "l3-total-add.csv"
    if not l2_path.exists() or not l3_path.exists():
        raise FileNotFoundError(
            f"expected {l2_path.name} and {l3_path.name} under {data_dir}; "
            "see data/README.md for how to fetch and unzip the dataset"
        )

    l2 = _read_csv(l2_path)
    benign = l2[l2["Label"] == "Benign"].copy()
    benign["label"] = "Benign"
    benign["tool"] = BENIGN_TOOL_LABEL

    l3 = _read_csv(l3_path)
    malicious = l3.copy()
    malicious["label"] = "Malicious"
    malicious["tool"] = malicious["Label"]  # l3's Label column is the tool name

    combined = pd.concat([benign, malicious], ignore_index=True)
    before = len(combined)
    combined = combined.dropna(subset=list(BEHAVIORAL_FEATURES))
    dropped = before - len(combined)
    if dropped:
        # Not raised as an error: a small, class-balanced amount of missing
        # data is a normal thing to drop. Silence here would just hide it.
        pass

    return DoHDataset(frame=combined.reset_index(drop=True))
